library(MASS)
plot(MPG.highway ~ Weight, data = Cars93, pch = 1, main = "pch = 1")
plot(MPG.highway ~ Weight, data = Cars93, pch = 2, main = "pch = 2")
plot(MPG.highway ~ Weight, data = Cars93, pch = 3, main = "pch = 3")
plot(MPG.highway ~ Weight, data = Cars93, pch = 4, main = "pch = 4")
plot(MPG.highway ~ Weight, data = Cars93, pch = 5, main = "pch = 5")
plot(MPG.highway ~ Weight, data = Cars93, pch = 6, main = "pch = 6")

par(mfrow = c(1,1))
plot(MPG.highway ~ Weight, data = Cars93, pch = 19, cex = 4, main = "cex = 4")
plot(MPG.highway ~ Weight, data = Cars93, pch = "%", cex = 1, main = "cex = 4")
